sudo: required
services:
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t paulparas/docker-react .

script: 
  - "docker run -e CI=true paulparas/docker-react npm run test -- --coverage"
