sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t paulparas/docker-react .

script: 
  - "docker run -e CI=true paulparas/docker-react npm run test -- --coverage"

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: 'elasticbeanstalk-ap-south-1-052758471237'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY